# Generated by Django 5.0.14 on 2026-08-02 11:14

import django.db.models.deletion
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('networking', 'Networking & Setup'), ('repairs', 'Laptop & PC Repairs'), ('momo', 'Mobile Money & Vending'), ('general', 'General Inquiries')], default='general', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='LaptopBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('logo_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MoMoFeeTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('Telecel', 'Telecel Cash'), ('AT', 'AT Money'), ('ALL', 'All Operators')], default='ALL', max_length=20)),
                ('transaction_type', models.CharField(choices=[('cash_in', 'Cash In (Deposit)'), ('cash_out', 'Cash Out (Withdrawal)'), ('transfer', 'Send Money / Transfer')], default='cash_out', max_length=20)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('flat', 'Flat Fee')], default='percentage', max_length=15)),
                ('fee_value', models.DecimalField(decimal_places=2, help_text='Percentage e.g. 0.75 or Flat amount e.g. 5.00', max_digits=6)),
                ('max_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum fee cap if any', max_digits=8, null=True)),
            ],
            options={
                'ordering': ['operator', 'transaction_type', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='NetworkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('target_audience', models.CharField(help_text='e.g. Home Wi-Fi, SMB Office, Enterprise', max_length=100)),
                ('price_estimate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('icon_name', models.CharField(default='wifi', max_length=50)),
                ('features_list', models.TextField(help_text='Enter items separated by newlines')),
                ('is_popular', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['price_estimate'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(default=services.models.generate_booking_ref, max_length=15, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('service_type', models.CharField(help_text='e.g. Networking, Laptop Repair, MoMo Vending', max_length=100)),
                ('details', models.TextField(help_text='Issue description, device model, or networking requirement')),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Ticket Received'), ('diagnostics', 'Under Diagnostics'), ('in_progress', 'Repair / Installation in Progress'), ('testing', 'Quality Testing'), ('ready', 'Ready for Pickup / Operational'), ('completed', 'Completed')], default='received', max_length=20)),
                ('status_notes', models.TextField(blank=True, help_text='Technician progress notes shown to customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='wrench', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_role', models.CharField(help_text='e.g. Small Business Owner, Resident, Tech Lead', max_length=100)),
                ('service_used', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField()),
                ('is_verified', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='LaptopRepairIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=150)),
                ('estimated_cost_min', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estimated_cost_max', models.DecimalField(decimal_places=2, max_digits=8)),
                ('turnaround_time', models.CharField(default='Same Day (2-4 hrs)', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='services.laptopbrand')),
            ],
            options={
                'ordering': ['issue_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='check-circle', max_length=50)),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('badge_text', models.CharField(blank=True, max_length=50)),
                ('is_featured', models.BooleanField(default=True)),
                ('features_list', models.TextField(blank=True, help_text='Enter features separated by newlines')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory')),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
