# Generated by Django 5.2.16 on 2026-08-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_businessinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoMoFeeTier',
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='address',
            field=models.CharField(default='Tech Hub Street, Main Business District, Suite 4B', max_length=255),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='business_name',
            field=models.CharField(default='TechStyle Solutions', max_length=150),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='email',
            field=models.EmailField(default='support@techstylesolutions.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('web', 'Web Solutions & Apps'), ('cctv', 'CCTV & Security Systems'), ('networking', 'Networking & Infrastructure'), ('repairs', 'Laptop & PC Repairs'), ('general', 'General Inquiries')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='details',
            field=models.TextField(help_text='Issue description, project specs, or networking requirement'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service_type',
            field=models.CharField(help_text='e.g. Web Solutions, CCTV Installation, Networking, Laptop Repair', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('received', 'Ticket Received'), ('diagnostics', 'Under Assessment / Diagnostics'), ('in_progress', 'Development / Installation in Progress'), ('testing', 'Quality Testing & QA'), ('ready', 'Ready / Deployed'), ('completed', 'Completed')], default='received', max_length=20),
        ),
    ]
