# Generated by Django 5.2.16 on 2026-08-04 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_delete_momofeetier_alter_businessinfo_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon_name', models.CharField(blank=True, help_text='Lucide icon name for visual badge', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Project Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('client_name', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('challenge', models.TextField(blank=True, help_text='Problem or challenge the client faced')),
                ('solution', models.TextField(blank=True, help_text='How TechStyle Solutions solved it')),
                ('results', models.TextField(blank=True, help_text='Outcomes, metrics, or impact achieved')),
                ('cover_image', models.ImageField(help_text='Primary showcase image', upload_to='portfolio/covers/')),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('project_duration', models.CharField(blank=True, help_text='e.g. 3 Weeks, Same Day', max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on home page featured strip')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_projects', to='services.servicecategory')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='services.projecttechnology')),
            ],
            options={
                'ordering': ['order', '-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_before', models.BooleanField(default=False, help_text="Mark as 'before' image for comparison")),
                ('is_after', models.BooleanField(default=False, help_text="Mark as 'after' image for comparison")),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.portfolioproject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
