# Generated by Django 5.2.16 on 2026-08-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_projecttechnology_portfolioproject_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorePillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='check-circle', max_length=50)),
                ('button_text', models.CharField(default='Explore', max_length=50)),
                ('button_link', models.CharField(help_text='URL or path, e.g. /services/', max_length=200)),
                ('features_list', models.TextField(blank=True, help_text='Enter features separated by newlines')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('suffix', models.CharField(blank=True, default='+', max_length=10)),
                ('label', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='about_us_footer',
            field=models.TextField(default='Your trusted partner for custom web solutions & software applications, HD CCTV security installations, network equipment sales & structured cabling, and laptop hardware repairs.'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='global_cta_text',
            field=models.TextField(default="Don't see exactly what you need? Our team builds custom solutions tailored to your business requirements."),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='global_cta_title',
            field=models.CharField(default='Need a Custom Solution?', max_length=150),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='hero_subtitle',
            field=models.TextField(default='From custom fullstack Django web applications and 24/7 HD CCTV security installations to enterprise network equipment sales and express hardware laptop repairs—we power your digital world.'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='hero_title',
            field=models.CharField(default='Web Apps, CCTV Systems & Network Solutions', max_length=200),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='seo_meta_description',
            field=models.TextField(default='TechStyle Solutions - Custom Web Applications & Software, HD CCTV Security Installations, Sale of Enterprise Networking Equipment, and Express Laptop Repairs.'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='seo_title_suffix',
            field=models.CharField(default='TechStyle Solutions - Web Solutions, CCTV Installations, Networking & Laptop Repairs', max_length=150),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Upload a custom logo to replace the default icon', null=True, upload_to='branding/logo/'),
        ),
    ]
