# Generated by Django 5.2.17 on 2026-08-21 17:43

import django.db.models.deletion
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_corepillar_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon_name', models.CharField(default='package', help_text='Lucide icon name', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Shop Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(default=services.models.generate_order_ref, max_length=15, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('delivery_address', models.TextField(help_text='Full delivery address')),
                ('notes', models.TextField(blank=True, help_text='Special instructions or notes')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Payment Received'), ('confirmed', 'Order Confirmed'), ('processing', 'Processing / Packing'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('status_notes', models.TextField(blank=True, help_text='Internal notes / updates shown to customer')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paystack_reference', models.CharField(blank=True, help_text='Paystack transaction reference', max_length=100)),
                ('payment_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='shop/products/')),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price in GHS', max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price (shown as strike-through if set)', max_digits=10, null=True)),
                ('badge_text', models.CharField(blank=True, help_text='e.g. Hot Deal, New Arrival, Limited Stock', max_length=50)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured/highlighted section')),
                ('specs_list', models.TextField(blank=True, help_text='Key specs separated by newlines')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='services.shopcategory')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Snapshot of product name at time of order', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.shoporder')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='services.shopproduct')),
            ],
        ),
    ]
