# Generated by Django 5.0.14 on 2026-08-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Perfect Solutions Tech & MoMo Hub', max_length=150)),
                ('phone_primary', models.CharField(default='+233 (0) 24 000 0000', max_length=30)),
                ('phone_secondary', models.CharField(blank=True, default='+233 (0) 50 000 0000', max_length=30)),
                ('whatsapp_number', models.CharField(default='233240000000', help_text='Number with country code for WhatsApp link e.g. 233240000000', max_length=30)),
                ('email', models.EmailField(default='support@perfectsolutions.tech', max_length=254)),
                ('address', models.CharField(default='Tech Hub Street, Main Business District, Shop #4 B', max_length=255)),
                ('opening_hours_weekday', models.CharField(default='8:00 AM - 7:00 PM', max_length=100)),
                ('opening_hours_saturday', models.CharField(default='9:00 AM - 6:00 PM', max_length=100)),
                ('opening_hours_sunday', models.CharField(default='Closed / Emergency Support', max_length=100)),
                ('announcement_banner', models.CharField(default='Open Today • 8:00 AM - 7:00 PM', help_text='Text shown in top header status bar', max_length=255)),
                ('facebook_url', models.URLField(blank=True, default='#')),
                ('instagram_url', models.URLField(blank=True, default='#')),
                ('twitter_url', models.URLField(blank=True, default='#')),
            ],
            options={
                'verbose_name': 'Business Info & Contact Details',
                'verbose_name_plural': 'Business Info & Contact Details',
            },
        ),
    ]
