# Generated by Django 5.2.16 on 2026-08-05 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_corepillar_sitemetric_businessinfo_about_us_footer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corepillar',
            options={'ordering': ['order'], 'verbose_name': 'Core Service', 'verbose_name_plural': 'Core Services'},
        ),
    ]
